### ISSUE TITLE
error mas

### ISSUE THREAD

**Issue by jekpot1337xOut** [ItsMeLBoy/AWCREC#2]
[ ACCESS DENIED ] - AKIAASFDASD|ASDA+ASDASDDCVFS|us-east-1 : CANT ACCESS AWS SES
[ ? ] CHECKING ACCESS AWS IAM
./Awcrec.sh: line 110: AWS_Create_Login_Profile: command not found

error mas

**Comment by noolep** [comment]
Usahain folder "files" satu didalam 1 folder Awcrec.sh

**Comment by jekpot1337xOut** [comment]
udah mas, ternyata mnta di dos2unix dlu ... makasih2 mas

**Comment by noolep** [comment]
Mantap
